repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: debug-statements
        name: Debug Statements
        description: Checks for debugger imports and py37+ `breakpoint()` calls

      - id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures that files end in a newline and only a newline.

      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.

      - id: mixed-line-ending
        name: Mixed Line Endings
        description: Replaces mixed line endings with the UNIX line ending.
        args: ["--fix=lf"]

      - id: fix-byte-order-marker
        name: Remove Byte Order Mark
        description: Removes UTF-8 byte order marker.

      - id: detect-private-key
        name: Detect Private Keys
        description: Checks for the presence of private keys.

      - id: check-illegal-windows-names
        name: Check Illegal Windows Names
        description: Checks for files that cannot be created on Windows.

      - id: check-case-conflict
        name: Check Case Conflict
        description: Checks for files that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.

      - id: check-added-large-files
        name: Check Large Files
        description: Prevent large files from being committed.
        args: ["--maxkb=500"]

  - repo: local
    hooks:
      - id: pyright
        name: Type Checking (pyright)
        description: Static type checking for Python
        entry: uv run pyright
        language: system
        types: [python]
        always_run: true

  - repo: local
    hooks:
      - id: bandit
        name: Security Issues (bandit)
        description: Find common security issues in Python code
        entry: uv tool run bandit src -r
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff-check
        name: Python Linting (ruff)
        description: Lints all discovered Python files, optionally fixing errors
        args: [--fix]

      - id: ruff-format
        name: Python Formatting (ruff)
        description: Formats all discovered Python files

  - repo: local
    hooks:
      - id: uv-lock
        name: UV Lock
        description: Ensure the uv lock file is up-to-date when committing changes
        entry: uv lock
        language: system
        pass_filenames: false
